export enum OdyBoss {
  BUMBA = 'Bumba',
  AREBATI = 'Arebati',
  MBOZE = 'Mboze',
  ONGO = 'Ongo',
  KALUNGA = 'Kalunga',
  NGAI = 'Ngai',
  XEVIOSO = 'Xevioso',
  HENWEN = 'Henwen',
  PROCNE = 'Procne',
  GIGELORUM = 'Gigelorum',
  MARMOKREBS = 'Marmokrebs',
  RASKOVNICHE = 'Raskovniche',
  ARISTAEUS = 'Aristaeus',
  GOGMAGOG = 'Gogmagog',
  U_BNAI = 'U Bnai',
  SGILI = 'Sgili',
  DEALAN_DHE = 'Dealan-dhe',
}
