export enum OdyBoss {
  BUMBA = 'BUMBA',
  AREBATI = 'AREBATI',
  MBOZE = 'MBOZE',
  ONGO = 'ONGO',
  KALUNGA = 'KALUNGA',
  NGAI = 'NGAI',
  XEVIOSO = 'XEVIOSO',
  HENWEN = 'HENWEN',
  PROCNE = 'PROCNE',
  GIGELORUM = 'GIGELORUM',
  MARMOKREBS = 'MARMOKREBS',
  RASKOVNICHE = 'RASKOVNICHE',
  ARISTAEUS = 'ARISTAEUS',
  GOGMAGOG = 'GOGMAGOG',
  U_BNAI = 'U_BNAI',
  SGILI = 'SGILI',
  DEALAN_DHE = 'DEALAN_DHE',
}

export const ODY_BOSS_INFO: {boss: OdyBoss, tier: number, prettyName: string}[] = [
  {boss: OdyBoss.BUMBA, tier: 4, prettyName: 'Bumba'},
  {boss: OdyBoss.AREBATI, tier: 3, prettyName: 'Arebati'},
  {boss: OdyBoss.MBOZE, tier: 3, prettyName: 'Mboze'},
  {boss: OdyBoss.ONGO, tier: 3, prettyName: 'Ongo'},
  {boss: OdyBoss.KALUNGA, tier: 3, prettyName: 'Kalunga'},
  {boss: OdyBoss.NGAI, tier: 3, prettyName: 'Ngai'},
  {boss: OdyBoss.XEVIOSO, tier: 3, prettyName: 'Xevioso'},
  {boss: OdyBoss.HENWEN, tier: 2, prettyName: 'Henwen'},
  {boss: OdyBoss.PROCNE, tier: 2, prettyName: 'Procne'},
  {boss: OdyBoss.GIGELORUM, tier: 2, prettyName: 'Gigelorum'},
  {boss: OdyBoss.MARMOKREBS, tier: 2, prettyName: 'Marmokrebs'},
  {boss: OdyBoss.RASKOVNICHE, tier: 2, prettyName: 'Raskovniche'},
  {boss: OdyBoss.ARISTAEUS, tier: 2, prettyName: 'Aristaeus'},
  {boss: OdyBoss.GOGMAGOG, tier: 1, prettyName: 'Gogmagog'},
  {boss: OdyBoss.U_BNAI, tier: 1, prettyName: 'U Bnai'},
  {boss: OdyBoss.SGILI, tier: 1, prettyName: 'Sgili'},
  {boss: OdyBoss.DEALAN_DHE, tier: 1, prettyName: 'Dealan-dhe'},
];
